/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.2 */

#include "messages.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(request, request, AUTO)


PB_BIND(response, response, AUTO)





