/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.2 */

#include "messages.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(request, request, 2)


PB_BIND(request_Ping, request_Ping, AUTO)


PB_BIND(request_Send, request_Send, AUTO)


PB_BIND(request_Subscribe, request_Subscribe, AUTO)


PB_BIND(request_Operation, request_Operation, AUTO)


PB_BIND(response, response, 2)


PB_BIND(response_OpResponse, response_OpResponse, AUTO)




