/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.2 */

#include "messages.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(request, request, AUTO)


PB_BIND(request_Ping, request_Ping, AUTO)


PB_BIND(request_Send, request_Send, AUTO)


PB_BIND(request_Request, request_Request, AUTO)


PB_BIND(request_Operation, request_Operation, AUTO)


PB_BIND(response, response, AUTO)


PB_BIND(response_Response, response_Response, AUTO)




